# Generated by Django 4.2.5 on 2023-09-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_game_apexabilitycheck_played_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="emoji_name",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
