# Generated by Django 4.2.5 on 2023-10-14 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_rename_apexabilitycheck_apexabilitycheckold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("stop_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayHistoryGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name="apexabilitycheckold",
            name="check_time_old_desc",
        ),
        migrations.AddField(
            model_name="playhistorygame",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.game"
            ),
        ),
        migrations.AddField(
            model_name="playhistorygame",
            name="target_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.playhistory"
            ),
        ),
        migrations.AddField(
            model_name="playhistory",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.player"
            ),
        ),
        migrations.AddIndex(
            model_name="playhistorygame",
            index=models.Index(
                fields=["target_history"], name="history_target_game_asc"
            ),
        ),
        migrations.AddIndex(
            model_name="playhistory",
            index=models.Index(fields=["-start_time"], name="check_time_desc"),
        ),
    ]
