# Generated by Django 4.2.5 on 2023-10-14 02:08

from django.db import migrations


def move_data_from_apexabilitycheck_to_playhistory(apps, schema_editor):
    apex = apps.get_model("web", "ApexabilityCheckOld")
    play = apps.get_model("web", "PlayHistory")
    play_game = apps.get_model("web", "PlayHistoryGame")

    current_play_map = {}
    for check in apex.objects.all():
        if check.entry_type == "start":
            current_play_map[check.player] = {
                "time": check.time,
                "played_game": check.played_game,
            }
        elif check.entry_type == "stop":
            try:
                current_play = current_play_map[check.player]
                new_play = play.objects.create(
                    player=check.player,
                    start_time=current_play["time"],
                    stop_time=check.time,
                )
                play_game.objects.create(
                    target_history=new_play, game=current_play["played_game"]
                )
            except KeyError:
                continue


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_playhistory_playhistorygame_and_more"),
    ]

    operations = [
        migrations.RunPython(move_data_from_apexabilitycheck_to_playhistory),
    ]
