# Generated by Django 4.2.5 on 2023-09-18 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.FileField(upload_to="screenshots/")),
                ("sent_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OW2UserImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.FileField(upload_to="user_images/")),
                (
                    "shown_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ow2db_web.screenshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OW2UniqueUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                (
                    "user_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ow2db_web.ow2userimage",
                    ),
                ),
            ],
        ),
    ]
