# Generated by Django 4.2.5 on 2023-09-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ow2db_web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ow2userimage",
            name="image",
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="image",
            field=models.BinaryField(),
        ),
    ]
