# Generated by Django 4.2.5 on 2023-09-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ow2db_web", "0002_alter_ow2userimage_image_alter_screenshot_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ow2userimage",
            old_name="shown_in",
            new_name="original_sc",
        ),
        migrations.AddField(
            model_name="ow2userimage",
            name="histogram",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
