# Generated by Django 4.2.5 on 2023-09-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ow2db_web", "0003_rename_shown_in_ow2userimage_original_sc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ow2uniqueuser",
            name="user_image",
        ),
        migrations.AddField(
            model_name="ow2userimage",
            name="ow2_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ow2db_web.ow2uniqueuser",
            ),
        ),
    ]
