# Generated by Django 4.2.5 on 2023-09-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ow2db_web", "0004_remove_ow2uniqueuser_user_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ow2userimage",
            name="ow2_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ow2db_web.ow2uniqueuser",
            ),
        ),
    ]
