# Generated by Django 4.2.5 on 2023-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ow2db_web", "0005_alter_ow2userimage_ow2_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ow2uniqueuser",
            name="last_seen",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ow2userimage",
            name="histogram",
            field=models.FileField(blank=True, null=True, upload_to="ow2userhisto/"),
        ),
        migrations.AlterField(
            model_name="ow2userimage",
            name="image",
            field=models.FileField(upload_to="ow2userimages/"),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="image",
            field=models.FileField(upload_to="screenshots/"),
        ),
    ]
